component: http
name: react-notion-x-minimal

inputs:
  src:
    dist: ./
    hook: npm run build
    exclude:
      - .env
  faas:
    runtime: Nodejs12.16
    framework: nextjs
    name: ${name}
  apigw:
    protocols:
      - http
      - https
